// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPageCount(arg1) {
  return window['go']['main']['App']['GetPageCount'](arg1);
}

export function GetPdfPage(arg1, arg2) {
  return window['go']['main']['App']['GetPdfPage'](arg1, arg2);
}

export function GetPdfThumbnails(arg1) {
  return window['go']['main']['App']['GetPdfThumbnails'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
